{{- if .Values.global.acls.manageSystemACLs }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "consul.fullname" . }}-auth-method
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "consul.name" . }}
    chart: {{ template "consul.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    component: auth-method
  annotations:
    kubernetes.io/service-account.name: {{ template "consul.fullname" . }}-connect-injector-authmethod-svc-account
type: kubernetes.io/service-account-token
{{- end }}