FROM envoyproxy/envoy:v1.24.0

# override the existing default envoy.yaml
COPY ./envoy-config-static-server.yml etc/envoy/envoy.yaml

RUN chmod go+r /etc/envoy/envoy.yaml

RUN apt-get update \
    && apt-get install -y curl jq


CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]