FROM envoyproxy/envoy:v1.24.0

# override the existing default envoy.yaml
COPY ./envoy-config-static-client.yml etc/envoy/envoy.yaml

RUN chmod go+r /etc/envoy/envoy.yaml

CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]